//
// Body.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.Body

import Vapor


public final class Body: Content {

    public var users: [UUID]

    public init(users: [UUID]) { 
        self.users = users
    }

    public enum CodingKeys: String, CodingKey { 
        case users = "users"
    }

}
