//
// Chat.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.Chat

import Vapor


public final class Chat: Content {

    public var id: UUID
    public var createAt: Date
    public var updateAt: Date
    public var lastMessageAt: Date?
    public var type: ChatType
    /** Всегда есть у типов channel и group */
    public var name: String?
    /** Всегда есть у типов channel и group */
    public var image: String?
    /** Для group */
    public var creatorUsername: String?
    /** Всегда есть у типа direct */
    public var username: String?
    /** для channel и group */
    public var isPublic: Bool?

    public init(id: UUID, createAt: Date, updateAt: Date, lastMessageAt: Date?, type: ChatType, name: String?, image: String?, creatorUsername: String?, username: String?, isPublic: Bool?) { 
        self.id = id
        self.createAt = createAt
        self.updateAt = updateAt
        self.lastMessageAt = lastMessageAt
        self.type = type
        self.name = name
        self.image = image
        self.creatorUsername = creatorUsername
        self.username = username
        self.isPublic = isPublic
    }
}
