//
// ChatType.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.ChatType

import Vapor

public enum ChatType: String, Codable {
    case direct = "direct"
    case channel = "channel"
    case group = "group"
}