//
// CreateUserRequestBody.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.CreateUserRequestBody

import Vapor


public final class CreateUserRequestBody: Content {

    public var username: String
    public var name: String?
    public var avatar: String?

    public init(username: String, name: String?, avatar: String?) { 
        self.username = username
        self.name = name
        self.avatar = avatar
    }
}
