//
// CreateChatBody.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.CreateChatBody

import Vapor


public final class CreateChatBody: Content {

    public var type: ChatType
    /** Всегда есть у типов channel и group */
    public var name: String?
    /** Всегда есть у типов channel и group */
    public var image: String?
    /** Всегда есть у типа direct */
    public var userId: String?
    /** для channel и group */
    public var isPublic: Bool?

    public init(type: ChatType, name: String?, image: String?, userId: String?, isPublic: Bool?) { 
        self.type = type
        self.name = name
        self.image = image
        self.userId = userId
        self.isPublic = isPublic
    }
}
