//
// Message.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.Message

import Vapor


public final class Message: Content {

    public var id: Int
    /** пока есть везде */
    public var senderId: String?
    public var text: String?
    public var createAt: Date
    public var updateAt: Date?

    public init(id: Int, senderId: String?, text: String?, createAt: Date, updateAt: Date?) { 
        self.id = id
        self.senderId = senderId
        self.text = text
        self.createAt = createAt
        self.updateAt = updateAt
    }
}
