//
// Message.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.Message

import Vapor


public final class Message: Content {

    public var id: Int
    /** пока есть везде */
    public var senderId: UUID?
    public var text: String?
    public var createAt: Date
    public var updateAt: Date?

    public init(id: Int, senderId: UUID?, text: String?, createAt: Date, updateAt: Date?) { 
        self.id = id
        self.senderId = senderId
        self.text = text
        self.createAt = createAt
        self.updateAt = updateAt
    }

    public enum CodingKeys: String, CodingKey { 
        case id = "id"
        case senderId = "sender_id"
        case text = "text"
        case createAt = "create_at"
        case updateAt = "update_at"
    }

}
