//
// Point.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.Point

import Vapor


public final class Point: Content {

    public var latitude: Float?
    public var longitude: Float?

    public init(latitude: Float?, longitude: Float?) { 
        self.latitude = latitude
        self.longitude = longitude
    }

    public enum CodingKeys: String, CodingKey { 
        case latitude = "latitude"
        case longitude = "longitude"
    }

}
