//
// PositionArea.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.PositionArea

import Vapor


public final class PositionArea: Content {

    public var topLeft: Point?
    public var bottomRight: Point?

    public init(topLeft: Point?, bottomRight: Point?) { 
        self.topLeft = topLeft
        self.bottomRight = bottomRight
    }

    public enum CodingKeys: String, CodingKey { 
        case topLeft = "top_left"
        case bottomRight = "bottom_right"
    }

}
