//
// Position.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.Position

import Vapor


public final class Position: Content {

    public enum ModelType: String, Content { 
        case point = "point"
        case area = "area"
    }

    public var id: String
    public var createAt: Date
    public var name: String
    public var creatorId: String
    public var isPublic: Bool
    public var type: ModelType
    public var area: PositionArea?
    public var point: Point?

    public init(id: String, createAt: Date, name: String, creatorId: String, isPublic: Bool, type: ModelType, area: PositionArea?, point: Point?) { 
        self.id = id
        self.createAt = createAt
        self.name = name
        self.creatorId = creatorId
        self.isPublic = isPublic
        self.type = type
        self.area = area
        self.point = point
    }
}
