//
// PostMessage.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.PostMessage

import Vapor


public final class PostMessage: Content {

    public var text: String

    public init(text: String) { 
        self.text = text
    }

    public enum CodingKeys: String, CodingKey { 
        case text = "text"
    }

}
